import { useEffect, useState } from 'react'

const skills = [
  ['Programming & Data', ['Python', 'Pandas', 'NumPy', 'EDA', 'Data Preprocessing', 'Feature Engineering', 'Data Validation']],
  ['Machine Learning', ['Scikit-learn', 'Random Forest', 'XGBoost', 'KNN', 'Logistic Regression', 'Decision Trees', 'Isolation Forest', 'Model Evaluation', 'Hyperparameter Optimization']],
  ['Deep Learning', ['TensorFlow', 'Keras', 'PyTorch', 'CNN', 'ResNet', 'LSTM', 'BiLSTM', 'Attention Mechanisms', 'Transformers', 'Autoencoders']],
  ['Computer Vision & OCR', ['OpenCV', 'YOLO', 'Object Detection', 'Image Classification', 'Pose Estimation', 'DeepSORT', 'OCR', 'Roboflow']],
  ['Generative / Agentic AI', ['LLMs', 'RAG', 'Prompt Engineering', 'AI Agents', 'LangChain', 'LangGraph', 'n8n', 'Tool Calling', 'Embeddings', 'Vector Databases', 'ChromaDB']],
  ['AI Engineering & Deployment', ['FastAPI', 'REST APIs', 'PostgreSQL', 'AI Pipelines', 'Workflow Automation', 'Streamlit', 'Docker', 'Git/GitHub', 'Jupyter', 'Google Colab']],
]

const projects = [
  { id: 'gmail-auto-reply', category: ['genai', 'automation'], title: 'Gmail AI Auto-Reply & Triage System', sub: 'Intelligent Email Classification, Duplicate Prevention & Automated Responses', desc: 'An AI-powered Gmail automation workflow that monitors incoming emails, extracts and classifies messages, prevents duplicate or self-triggered responses, and conditionally sends automated in-thread replies while maintaining a complete audit log.', flow: 'Gmail Trigger -> Extract Email Data -> Loop Prevention -> Duplicate Check -> AI Classification -> Auto-Reply Decision -> Send Reply / Log -> Error Notification', tags: ['n8n', 'Gmail', 'OpenAI', 'GPT-4o-mini', 'Google Sheets', 'Telegram', 'AI Email Automation', 'Email Classification', 'OAuth2'], case: { Problem: 'Managing incoming emails manually can be time-consuming when inboxes contain automated notifications, newsletters, no-reply messages, and repetitive conversations.', Approach: 'Built an end-to-end n8n workflow that polls Gmail, extracts sender and message information, prevents self-triggered and automated emails, checks Google Sheets for duplicate replies, and uses OpenAI GPT-4o-mini to classify messages.', Evaluation: 'Validated email classification, loop prevention, duplicate thread detection, conditional reply decisions, audit logging, and error-handling paths.', Results: 'A fully automated Gmail triage and response pipeline that filters irrelevant messages, identifies genuine inquiries, sends contextual acknowledgements, prevents duplicates, and maintains a structured record.', Deployment: 'Orchestrated in n8n using Gmail and Google Sheets OAuth2, OpenAI API integration, and Telegram failure notifications.' } },
  { id: 'custom-agent', category: ['genai', 'agents', 'automation'], title: 'WhatsApp AI Real Estate Lead Qualification Agent', sub: 'Conversational Lead Qualification, Nurturing & Automated Meeting Booking', desc: 'An AI-powered WhatsApp agent that engages real-estate prospects, understands their requirements, qualifies leads based on property preferences, budget and timeline, nurtures unqualified prospects, and automatically books qualified consultations through Google Calendar.', flow: 'WhatsApp Message -> Message Extraction -> AI Agent -> Conversational Memory -> Lead Qualification -> Qualification Decision -> Calendar Booking / Lead Nurturing -> WhatsApp Notification & Reply', tags: ['n8n', 'AI Agents', 'WhatsApp', 'Google Gemini', 'Gemini 2.5 Flash-Lite', 'Lead Generation', 'Lead Qualification', 'Real Estate Automation', 'Conversational AI', 'Google Calendar', 'LangChain', 'LLM'], case: { Problem: 'Manually qualifying WhatsApp leads, collecting property requirements, following up, and scheduling consultations is time-consuming and inconsistent.', Approach: 'Built a conversational n8n agent with memory that asks qualification questions one at a time, normalizes property type, location, purpose, budget, and timeline, and determines whether a lead is ready for escalation.', Evaluation: 'Validated structured agent output, budget and timeline normalization, qualification rules, conversational state tracking, and qualified-versus-nurture paths.', Results: 'An automated real-estate funnel that engages prospects, qualifies high-intent leads, books consultations, notifies brokers, and nurtures prospects who are not ready.', Deployment: 'Orchestrated in n8n with WhatsApp, Google Gemini 2.5 Flash-Lite, conversational memory, Google Calendar, and WhatsApp notifications.' } },
  { id: 'ai-job-search-agent', category: ['genai', 'agents', 'automation'], title: 'AI Job Search & Career Agent', sub: 'Intelligent Job Search, ATS Resume Scoring & AI Email Generation', desc: 'An AI-powered career assistant that searches for relevant jobs across Remote, Onsite, Hybrid, or Any work modes, analyzes resume-job compatibility with ATS scoring, and generates personalized application emails.', flow: 'Job Search Preferences -> AI Job Search -> Listing Extraction -> Work Mode Filtering -> Resume & Job Analysis -> ATS Scoring -> AI Email Generation -> Application Support', tags: ['Python', 'Streamlit', 'AI Agents', 'LLM', 'Groq', 'Tavily', 'ATS Scoring', 'Job Search Automation', 'Resume Analysis', 'Email Generation', 'Docker', 'FastAPI', 'LangGraph'], case: { Problem: 'Finding relevant jobs manually and preparing a tailored application for every opportunity takes significant time.', Approach: 'Built an AI job-search application that extracts company, location, work mode, and other listing details, filters by preference, analyzes resume-job compatibility, calculates ATS scores, and generates application emails.', Evaluation: 'Validated structured listing extraction and work-mode filtering, then assessed resume-job matching through ATS scoring and AI analysis.', Results: 'A practical career assistant that streamlines discovery, identifies relevant opportunities, provides ATS-based matching, and generates personalized emails.', Deployment: 'Containerized the Streamlit application with Docker, with optional FastAPI and LangGraph backend support for REST deployment.' } },
  { id: 'fracture', category: ['cv', 'deep-learning', 'medical-ai'], title: 'AI Bone Fracture Detection', sub: 'YOLO11-Based X-Ray Fracture Localization & Classification', desc: 'A deep learning computer vision system for detecting and localizing bone fractures in X-ray images using YOLO11m, class-balancing augmentation, optimized training, and deployment-ready exports.', flow: 'X-Ray Images -> Dataset Analysis -> Class Balancing & Augmentation -> YOLO11m Training -> Fracture Detection -> Bounding Box Localization -> Model Validation -> ONNX / TorchScript Export', tags: ['COMPUTER VISION', 'MEDICAL AI', 'YOLO11', 'YOLO11m', 'PyTorch', 'Ultralytics', 'Albumentations', 'OpenCV', 'Object Detection', 'Data Augmentation', 'Class Balancing', 'ONNX', 'TorchScript', 'Kaggle'], case: { Problem: 'Accurate fracture localization must handle class imbalance while remaining suitable for practical deployment.', Approach: 'Built a YOLO11m pipeline on the Bone Fractures Detection dataset with Albumentations, class balancing, 768px training, AdamW, cosine scheduling, mixed precision, mosaic augmentation, and early stopping.', Evaluation: 'Evaluated with Ultralytics detection metrics and a normalized confusion matrix across fracture classes.', Results: 'Developed an optimized detector that identifies fracture regions with bounding boxes and preserves complete training and validation artifacts.', Deployment: 'Exported the best model to ONNX and TorchScript for integration into different inference environments.' } },
  { id: 'hybrid-ids', category: ['ml', 'deep-learning', 'cybersecurity'], title: 'Optimized Hybrid Intrusion Detection System', sub: 'Supervised Classification + Autoencoder Anomaly Detection for Zero-Day Attacks', desc: 'A hybrid deep learning intrusion detection system that combines supervised attack classification with global reconstruction-error and feature-specific anomaly detection.', flow: 'UNSW-NB15 Network Traffic -> Feature Selection & Cleaning -> Zero-Day Fuzzer Separation -> Standard Scaling -> Supervised IDS + Benign Autoencoder -> Global-MSE Detection + FSVT Detection -> Hybrid Score Optimization -> Attack / Zero-Day Detection', tags: ['Python', 'TensorFlow', 'Keras', 'Scikit-Learn', 'Pandas', 'NumPy', 'Deep Learning', 'Intrusion Detection', 'Cybersecurity AI', 'Autoencoder', 'Anomaly Detection', 'UNSW-NB15', 'Zero-Day Detection', 'Feature-Specific Voting', 'Hybrid IDS'], case: { Problem: 'Traditional IDS models can detect known attacks yet miss unseen or zero-day threats.', Approach: 'Built a hybrid IDS using 18 UNSW-NB15 network-flow features, a supervised neural network, a benign-only autoencoder, Global-MSE, Feature-Specific Voting Thresholds, and optimized hybrid weights.', Evaluation: 'Compared supervised, Global-MSE, FSVT, and hybrid models using accuracy, precision, recall, F1, false-positive rate, confusion matrices, ROC-AUC, and zero-day detection rate.', Results: 'Produces a unified intrusion score for conventional attacks and dedicated zero-day Fuzzer analysis.', Deployment: 'Saves Keras models, StandardScaler, FSVT thresholds, feature configuration, hybrid weights, detection thresholds, and evaluation artifacts for reuse.' } },
  { id: 'network-anomaly-detection', category: ['ml', 'deep-learning', 'cybersecurity'], title: 'Network Traffic Anomaly & Intrusion Detection', sub: 'Hybrid Supervised and Unsupervised Attack Detection', desc: 'A comprehensive intrusion detection system that classifies network traffic using ensemble learning, unsupervised anomaly detection, and sequential deep learning models.', flow: 'Network Traffic Data -> Data Cleaning & Label Normalization -> Feature Scaling -> Binary & Multiclass Classification -> Anomaly Detection -> Sequential LSTM Analysis -> Autoencoder Reconstruction -> Model Comparison', tags: ['Python', 'Scikit-Learn', 'Random Forest', 'XGBoost', 'Isolation Forest', 'LSTM', 'Autoencoder', 'TensorFlow', 'Keras', 'Anomaly Detection', 'Intrusion Detection', 'Cybersecurity', 'Network Traffic Analysis', 'Binary Classification', 'Multiclass Classification'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Large traffic volumes make it difficult to distinguish benign activity, malicious behavior, and anomalies with one approach.', Approach: 'Built a pipeline with cleaning, label normalization, missing-value handling, duplicate removal, scaling, Random Forest, XGBoost, Isolation Forest, Autoencoder, and LSTM analysis.', Evaluation: 'Compared binary and multiclass models using accuracy, precision, recall, F1, ROC-AUC, confusion matrices, reports, reconstruction thresholds, and training time.', Results: 'A comparative framework for conventional classification and unsupervised anomaly detection.', Deployment: 'Saves scalers, label encoders, classifiers, XGBoost, Isolation Forest, LSTM, and Autoencoder artifacts for future inference.' } },
  { id: 'crop-yield-prediction', category: ['ml'], title: 'Crop Yield Prediction Model', sub: 'Soil, Weather & Fertilizer-Based Yield Prediction', desc: 'A machine-learning regression model that predicts crop yield from fertilizer, temperature, and soil nutrient features using Random Forest.', flow: 'Agricultural Data -> Exploratory Analysis -> Feature Analysis -> Random Forest Regression -> Yield Prediction -> Error Analysis -> Cross-Validation', tags: ['Python', 'Pandas', 'Scikit-Learn', 'Random Forest', 'Regression', 'Agricultural AI', 'Crop Yield Prediction', 'Data Visualization', 'Joblib'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Crop yield depends on interacting agricultural and environmental factors.', Approach: 'Analyzed fertilizer, temperature, and soil nutrient measurements through correlation and feature visualizations before training a Random Forest regressor.', Evaluation: 'Used MSE, MAE, R2, actual-versus-predicted analysis, residuals, feature importance, and 5-fold cross-validation.', Results: 'Estimates crop yield while identifying the relative importance of input features.', Deployment: 'Serializes the trained model with Joblib as crop_model.pkl for reuse.' } },
  { id: 'sentiment-analysis', category: ['deep-learning', 'nlp'], title: 'IMDB Sentiment Analysis', sub: 'LSTM-Based Text Classification with Attention', desc: 'A deep-learning sentiment model that classifies movie reviews as positive or negative using LSTM networks with a custom attention mechanism.', flow: 'IMDB Reviews -> Text Cleaning & Normalization -> Text Vectorization -> Word Embeddings -> Stacked LSTM -> Attention Mechanism -> Dense Classification -> Sentiment Prediction', tags: ['Python', 'TensorFlow', 'Keras', 'NLP', 'LSTM', 'Attention Mechanism', 'Text Classification', 'Sentiment Analysis', 'Deep Learning', 'IMDB Dataset'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Sentiment models must capture contextual and sequential relationships while distinguishing positive and negative opinions.', Approach: 'Cleaned and tokenized IMDB reviews, then used embeddings, stacked LSTM layers, a custom attention mechanism, and class weighting.', Evaluation: 'Measured validation accuracy, precision, recall, F1, and confusion matrix performance with early stopping.', Results: 'An end-to-end sentiment classifier that uses attention to focus on important sequential text information.', Deployment: 'The trained model and vectorization pipeline can be reused for inference on new reviews.' } },
  { id: 'boxing-detection', category: ['cv', 'deep-learning'], title: 'Real-Time Boxing & Fight Detection System', sub: 'YOLO-Based Person Detection, DeepSORT Tracking & Fight Analysis', desc: 'A real-time system that detects people, tracks identities, and identifies potential fights from video using spatial proximity.', flow: 'Video Input -> Frame Processing -> YOLO Person Detection -> DeepSORT Tracking -> Person Proximity Analysis -> Fight Detection -> Annotated Video Output', tags: ['Python', 'YOLO26', 'DeepSORT', 'OpenCV', 'NumPy', 'Ultralytics', 'Object Detection', 'Multi-Object Tracking'], case: { Problem: 'Manual analysis makes it difficult to track individuals and identify fighting interactions consistently.', Approach: 'Processed video with YOLO26 and DeepSORT, then analyzed distances between tracked person centers against a configured proximity threshold.', Evaluation: 'Reviewed person counts, track IDs, bounding-box continuity, and fight alerts across video frames.', Results: 'Detects people, maintains identities, counts tracked individuals, and flags potential fights with on-screen alerts.', Deployment: 'Implemented with Python, OpenCV, Ultralytics YOLO, and DeepSORT; annotated results are exported as MP4.' } },
  { id: 'traffic-detection', category: ['cv', 'deep-learning'], title: 'Real-Time Traffic Detection & Monitoring', sub: 'YOLOv8 Object Detection, ByteTrack & Traffic Analytics', desc: 'A real-time system that detects and tracks vehicles and pedestrians, estimates speed, monitors density, and identifies potential accidents.', flow: 'Video Input -> Frame Processing -> YOLOv8 Detection -> Class Filtering -> ByteTrack Tracking -> Speed Estimation -> Accident Detection -> Traffic Analytics & Heatmap', tags: ['Python', 'YOLOv8', 'ByteTrack', 'OpenCV', 'Ultralytics', 'Supervision', 'NumPy', 'Pandas', 'Object Detection', 'Multi-Object Tracking', 'Speed Estimation', 'Traffic Analytics'], case: { Problem: 'Raw traffic video makes it difficult to identify road users, track movement, estimate speed, and monitor behavior continuously.', Approach: 'Used YOLOv8 and ByteTrack for detection and persistent identities, then derived speed, accident alerts, density heatmaps, and traffic analytics from trajectories.', Evaluation: 'Analyzed detection confidence, tracking IDs, speed statistics, accident alerts, traffic density, and processing FPS.', Results: 'A traffic-monitoring pipeline that tracks road users, displays speed and IDs, flags potential accidents, and generates analytics.', Deployment: 'Implemented with Python, YOLOv8, ByteTrack, OpenCV, and Supervision; annotated video is exported as MP4.' } },
]

const filters = [['all', 'All'], ['ml', 'Machine Learning'], ['dl', 'Deep Learning'], ['cv', 'Computer Vision'], ['agents', 'Agentic AI']]
const categoryLabels = { ml: 'Machine Learning', dl: 'Deep Learning', 'deep-learning': 'Deep Learning', cv: 'Computer Vision', agents: 'Agentic AI', genai: 'Agentic AI', automation: 'Agentic AI', 'medical-ai': 'Computer Vision', cybersecurity: 'Machine Learning', nlp: 'Deep Learning' }
const categoryAliases = { 'deep-learning': 'dl', genai: 'agents', automation: 'agents', 'medical-ai': 'cv', cybersecurity: 'ml', nlp: 'dl' }
const getProjectCategories = project => [...new Set(project.category.map(category => categoryAliases[category] || category).filter(category => categoryLabels[category]))]
const featuredProjectIds = ['gmail-auto-reply', 'custom-agent', 'fracture', 'network-anomaly-detection']
/*
  { id: 'rag', category: ['genai', 'rag'], title: 'AI Knowledge Assistant', sub: 'Advanced RAG Pipeline for Document Q&A', desc: 'A full-stack retrieval-augmented generation system designed to answer questions from documents using intelligent retrieval and LLM-based generation.', flow: 'PDF -> OCR Parsing -> Chunking -> Embeddings -> Vector DB -> Hybrid Retrieval -> Reranking -> LLM', tags: ['Python', 'RAG', 'LLMs', 'Embeddings', 'Vector DB', 'ChromaDB', 'OCR', 'FastAPI'], case: { Problem: 'Answering questions accurately from long, unstructured documents without the response drifting away from the source material.', Approach: 'OCR-aware extraction, chunk embeddings, hybrid retrieval, reranking, and an LLM that generates source-cited answers.', Evaluation: 'Retrieval quality and answer grounding were assessed by checking generated answers against cited source chunks.', Results: 'A working end-to-end assistant capable of hybrid retrieval, reranking, and source-cited responses.', Deployment: 'Exposed through a FastAPI backend for application integration.' } },
  { id: 'gmail-auto-reply', category: ['genai'], title: 'Gmail AI Auto-Reply & Triage System', sub: 'Automated Intelligent Inbox Management & Context-Aware Auto-Reply', desc: 'An intelligent Gmail workflow that classifies incoming messages, prevents duplicate responses, and conditionally sends context-aware replies to genuine inquiries.', flow: 'Gmail Trigger -> Extract Email Data -> Loop Prevention -> Check Duplicate -> AI Classification -> Smart Reply Decision -> Send Reply / Log', tags: ['n8n', 'Gmail', 'Google Sheets', 'Groq', 'Llama 3.3 70B', 'AI Classification', 'OAuth2'], case: { Problem: 'Managing high-volume Gmail inboxes manually requires constant triage, leading to delayed responses to important inquiries and wasted time reading automated notifications, newsletters, and spam.', Approach: 'Real-time inbox polling via n8n, combined with automated loop prevention, Google Sheets duplicate-checking, and Groq-hosted Llama 3.3 70B LLM classification to categorize emails and conditionally auto-reply directly in-thread.', Evaluation: 'Classification accuracy, auto-reply conservative thresholding, duplicate-reply suppression, and error handling were verified using logged thread records in Google Sheets across varied email types.', Results: 'A fully automated triage and response system that skips newsletters and automated mail, responds contextually to genuine inquiries, and maintains a detailed audit log.', Deployment: 'Orchestrated end-to-end within n8n using OAuth2 integrations for Gmail and Google Sheets, alongside Groq API access for LLM processing.' } },
  { id: 'custom-agent', category: ['genai'], title: 'Custom AI Agent / Agentic AI System', sub: 'Tool-Using Workflow Automation Agent', desc: 'An agentic AI system that interprets a user goal, selects tools, executes multi-step actions, and returns a grounded result.', flow: 'User Goal -> Intent Planning -> Tool Selection -> Tool Calling -> State Tracking -> Validated Response', tags: ['Python', 'LLMs', 'AI Agents', 'LangChain', 'LangGraph', 'Tool Calling'], case: { Problem: 'Multi-step operational requests often require repeated manual handoffs between search, data, and workflow tools.', Approach: 'An LLM-driven agent uses LangChain and LangGraph to plan tasks, select approved tools, track state, and validate outputs before responding.', Evaluation: 'Tool-selection accuracy, state continuity, response grounding, and graceful handling of unavailable tools were tested across representative workflows.', Results: 'A reusable agent pattern for orchestrating structured tasks while keeping tool actions observable and controlled.', Deployment: 'Designed for integration into Python applications and workflow automation environments.' } },
  { id: 'knowledge-base-assistant', category: ['genai'], title: 'Intelligent Document / Knowledge Base AI Assistant', sub: 'Semantic Search & Contextual Knowledge Retrieval', desc: 'A knowledge-base assistant that turns internal documents into searchable, context-rich answers for everyday decision support.', flow: 'Knowledge Sources -> Parsing -> Chunking -> Embeddings -> ChromaDB -> Semantic Retrieval -> LLM Response', tags: ['Python', 'RAG', 'Embeddings', 'Vector Databases', 'ChromaDB', 'Prompt Engineering'], case: { Problem: 'Important organizational knowledge is difficult to reuse when it is distributed across long documents and disconnected sources.', Approach: 'Documents are parsed, chunked, embedded, and indexed in ChromaDB before relevant context is passed to an LLM with grounded prompting.', Evaluation: 'Retrieval relevance, answer faithfulness, citation coverage, and response consistency were reviewed against curated questions.', Results: 'A practical knowledge assistant that provides concise, context-aware answers from indexed source material.', Deployment: 'Structured for deployment as an internal AI application with a retrievable document index.' } },
  { id: 'fracture', category: ['cv'], title: 'AI Bone Fracture Detection', sub: 'YOLO-based Medical Object Detection', desc: 'A computer vision system for detecting bone fractures from X-ray images using YOLO-based object detection.', flow: 'X-Ray -> YOLO Detection -> Fracture Bounding Box -> Prediction', tags: ['COMPUTER VISION', 'MEDICAL AI', 'YOLOv8', 'PyTorch', 'Ultralytics', 'OpenCV', 'Google Colab'], metric: '99.5%', metricLabel: 'mAP@50', case: { Problem: 'Detecting bone fractures in X-ray images to support faster, more consistent diagnostic review.', Approach: 'A YOLOv8 object detection model was trained to localize and classify fracture regions with bounding boxes.', Evaluation: 'Evaluated using mAP@50, a standard object detection metric.', Results: 'Achieved 99.5% mAP@50 on the evaluation set.' } },
  { id: 'churn-prediction', category: ['ml'], title: 'Predictive Analytics / Customer Churn Prediction', sub: 'Retention Risk Modeling & API Inference', desc: 'A predictive analytics system that identifies customers at risk of churn and turns model scores into actionable retention signals.', flow: 'Data Ingestion -> Preprocessing & Encoding -> Feature Engineering -> Model Training (XGBoost/LightGBM) -> Threshold Tuning -> API Inference', tags: ['Python', 'XGBoost', 'LightGBM', 'Scikit-Learn', 'Pandas', 'FastAPI'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Customer churn is costly to detect after the fact, while manual review makes it difficult to prioritize high-risk accounts consistently.', Approach: 'Structured customer data was encoded and transformed into behavioral features, then modeled with XGBoost and LightGBM. Threshold tuning aligned predictions with retention-team priorities.', Evaluation: 'Performance was assessed using classification metrics, probability calibration, and threshold analysis to balance missed churners against unnecessary interventions.', Results: 'A reusable churn-risk scoring workflow that ranks customers for proactive retention outreach and exposes predictions through an inference API.', Deployment: 'Packaged behind a FastAPI endpoint with placeholders for a live demo and GitHub repository integration.' } },
  { id: 'predictive-maintenance', category: ['ml'], title: 'Predictive Maintenance / Machinery Anomaly Detection', sub: 'Sensor-Based Failure Risk Monitoring', desc: 'A machine-learning monitoring system that detects abnormal machinery behavior and raises alerts before failures interrupt operations.', flow: 'Sensor Time-Series Data -> Feature Extraction -> Random Forest / Isolation Forest -> Threshold Evaluation -> Real-Time Alerting', tags: ['Python', 'Scikit-Learn', 'Random Forest', 'Time-Series Analysis', 'Docker', 'Flask'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Unexpected machinery failures create downtime and maintenance costs when sensor abnormalities are discovered too late.', Approach: 'Sensor time-series data was converted into statistical and temporal features, then evaluated with Random Forest and Isolation Forest models for supervised and unsupervised anomaly detection.', Evaluation: 'Alert thresholds were tested against known failure patterns and normal operating windows, with emphasis on reducing false alarms while preserving failure recall.', Results: 'A real-time anomaly monitoring workflow that turns sensor signals into interpretable maintenance alerts.', Deployment: 'Containerized with Docker and served through Flask for integration with plant monitoring systems.' } },
  { id: 'credit-risk', category: ['ml'], title: 'Credit Scoring & Risk Assessment Model', sub: 'Explainable Lending Risk Prediction', desc: 'An explainable credit-risk model that estimates borrower risk while exposing the factors behind each prediction.', flow: 'Financial Data Pipeline -> Missing Value Imputation -> Feature Selection -> Logistic Regression / Gradient Boosting -> Model Explainability (SHAP) -> Inference API', tags: ['Python', 'Scikit-Learn', 'SHAP', 'Pandas', 'FastAPI', 'Streamlit'], links: ['[Live Demo Link]', '[GitHub Repository]'], case: { Problem: 'Credit decisions need consistent risk estimates while remaining understandable to analysts and applicants.', Approach: 'Financial records were imputed and reduced to stable predictive features, then compared across Logistic Regression and Gradient Boosting models with SHAP explanations for individual predictions.', Evaluation: 'Models were compared using discrimination, calibration, threshold behavior, and explanation consistency across borrower profiles.', Results: 'An auditable risk assessment workflow that combines predictive scoring with human-readable feature contributions.', Deployment: 'Served through a FastAPI inference layer with a Streamlit interface for reviewing scores and SHAP explanations.' } },
  { id: 'network-anomaly', category: ['ml'], title: 'Network Traffic Anomaly Detection', sub: 'Comparative Cybersecurity Model Evaluation', desc: 'A machine-learning system that compares classical and deep-learning approaches for detecting anomalous network traffic.', flow: 'Network Data -> Cleaning & Features -> Model Comparison -> Threshold Evaluation -> Anomaly Decision', tags: ['XGBoost', 'Random Forest', 'LSTM', 'Isolation Forest', 'Autoencoder', 'Model Evaluation'], metric: '99.59%', metricLabel: 'Accuracy · 99.96% ROC-AUC', case: { Problem: 'Network traffic requires reliable anomaly detection across classification and unsupervised scenarios without treating every unusual event as malicious.', Approach: 'XGBoost, Random Forest, LSTM, Isolation Forest, and Autoencoder approaches were trained and compared across structured traffic data.', Evaluation: 'Model comparison used accuracy, ROC-AUC, anomaly thresholds, and error analysis to assess both predictive quality and operational tradeoffs.', Results: 'XGBoost achieved 99.59% accuracy and 99.96% ROC-AUC on the evaluation data.', Deployment: 'Designed as an evaluated ML pipeline that can expose anomaly decisions to monitoring or security workflows.' } },
  { id: 'cnn-classification', category: ['dl'], title: 'CNN-Based Image Classification System', sub: 'Visual Recognition with Convolutional Networks', desc: 'A deep-learning image classification workflow using CNN and ResNet architectures to learn robust visual representations.', flow: 'Image Dataset -> Augmentation -> CNN / ResNet Training -> Validation -> Class Prediction', tags: ['Python', 'TensorFlow', 'Keras', 'CNN', 'ResNet', 'Image Classification'], case: { Problem: 'Image collections need consistent automated classification when manual labeling is slow and difficult to scale.', Approach: 'Images were prepared with preprocessing and augmentation, then used to train and compare CNN and ResNet-based classifiers.', Evaluation: 'Validation accuracy, class-level performance, confusion analysis, and generalization across held-out images were reviewed.', Results: 'A reusable neural image-classification pipeline aligned with the demonstrated TensorFlow, Keras, CNN, and ResNet skill set.', Deployment: 'Structured for notebook experimentation and application inference.' } },
  { id: 'sequence-modeling', category: ['dl'], title: 'LSTM / BiLSTM Sequence Modeling', sub: 'Temporal Pattern Learning for Sequential Data', desc: 'A sequence-modeling workflow that learns temporal dependencies with recurrent neural networks and bidirectional context.', flow: 'Sequential Data -> Windowing -> Feature Scaling -> LSTM / BiLSTM Training -> Sequence Evaluation -> Prediction', tags: ['Python', 'TensorFlow', 'Keras', 'LSTM', 'BiLSTM', 'Sequence Modeling'], case: { Problem: 'Sequential signals contain time-dependent relationships that static models can miss.', Approach: 'Sequences were windowed and scaled before comparing LSTM and BiLSTM architectures for temporal representation learning.', Evaluation: 'Predictions were assessed across held-out sequences using error analysis and stability across window sizes.', Results: 'A practical recurrent modeling pattern for sequence prediction and temporal anomaly signals.', Deployment: 'Prepared for integration into Python-based prediction pipelines.' } },
  { id: 'attention-transformer', category: ['dl'], title: 'Attention-Based Transformer Application', sub: 'Context-Aware Representation Learning', desc: 'A transformer-oriented deep-learning workflow that uses attention mechanisms to prioritize relevant context in complex inputs.', flow: 'Tokenized Input -> Embeddings -> Attention Mechanisms -> Transformer Layers -> Output Head -> Evaluation', tags: ['Python', 'TensorFlow', 'Keras', 'Attention Mechanisms', 'Transformers', 'NLP'], case: { Problem: 'Long or context-rich inputs require models that can focus on the most relevant relationships instead of relying only on local sequence memory.', Approach: 'Embedded inputs were processed through attention mechanisms and transformer layers before task-specific output prediction.', Evaluation: 'Context handling, validation performance, and error patterns across longer inputs were examined during structured experiments.', Results: 'A flexible attention-based modeling foundation for NLP and modern generative-AI experiments.', Deployment: 'Designed as an extensible deep-learning component for Python applications.' } },
  { id: 'autoencoder-anomaly', category: ['dl'], title: 'Autoencoder-Based Anomaly Detection', sub: 'Representation Learning for Unusual Patterns', desc: 'An unsupervised deep-learning workflow that learns normal behavior and identifies samples with elevated reconstruction error.', flow: 'Normal Data -> Feature Scaling -> Autoencoder Training -> Reconstruction Error -> Anomaly Threshold -> Alert', tags: ['Python', 'TensorFlow', 'Keras', 'Autoencoders', 'Anomaly Detection', 'Model Evaluation'], case: { Problem: 'Anomaly detection is difficult when labeled examples of every abnormal behavior are unavailable.', Approach: 'An autoencoder learned compact representations of normal data, then used reconstruction error to flag unusual samples.', Evaluation: 'Threshold behavior, reconstruction distributions, false alerts, and detection sensitivity were compared across validation data.', Results: 'A label-efficient anomaly detection approach that complements classical Isolation Forest and tree-based models.', Deployment: 'Prepared for batch or service-based anomaly scoring.' } },
  { id: 'vehicle-tracking', category: ['cv'], title: 'Real-Time Vehicle & Behavior Tracking System', sub: 'Multi-Object Tracking & Traffic Analytics', desc: 'A real-time computer vision system that tracks vehicles and analyzes movement and behavior across video feeds.', flow: 'Video Feed -> Frame Extraction -> YOLOv8 Object Detection -> DeepSORT Tracking -> Spatial Logic & Analytics -> Dashboard Display', tags: ['Python', 'YOLOv8', 'DeepSORT', 'OpenCV', 'PyTorch', 'Streamlit'], case: { Problem: 'Raw traffic video makes it difficult to measure vehicle movement, lane behavior, and object-level patterns consistently.', Approach: 'Video frames are processed with YOLOv8 detection, DeepSORT identity tracking, and spatial rules that transform trajectories into traffic analytics.', Evaluation: 'Detection quality, tracking continuity, identity switches, and analytics consistency were reviewed across varied traffic scenes.', Results: 'A live vehicle tracking workflow that produces persistent object identities and behavior metrics for dashboard display.', Deployment: 'Packaged as a Streamlit dashboard backed by Python, OpenCV, PyTorch, and real-time video processing.' } },
  { id: 'defect-inspection', category: ['cv'], title: 'Automated Defect Inspection for Manufacturing', sub: 'Edge-Ready Visual Quality Control', desc: 'A visual inspection pipeline that classifies manufacturing defects and turns model predictions into automated quality gates.', flow: 'Camera Stream -> Image Preprocessing -> Segmentation / Defect Classification -> Edge-Inference Logic -> Quality Gate Alerting', tags: ['Python', 'OpenCV', 'PyTorch', 'ResNet', 'TensorRT', 'FastAPI'], case: { Problem: 'Manual quality inspection can be slow and inconsistent when production lines require continuous defect screening.', Approach: 'Camera frames are normalized and passed through segmentation or ResNet-based defect classification, followed by edge inference logic for production decisions.', Evaluation: 'Defect classification, missed-defect rate, inference latency, and quality-gate reliability were evaluated across representative production samples.', Results: 'An automated inspection workflow that flags defective items quickly and produces consistent quality-control decisions.', Deployment: 'Optimized for edge inference with TensorRT and exposed through a FastAPI service for factory integration.' } },
  { id: 'attendance-verification', category: ['cv'], title: 'Smart Attendance & Face Verification System', sub: 'Identity Matching for Automated Attendance', desc: 'A face-verification system that matches enrolled identities from live streams and records attendance automatically.', flow: 'RTSP Stream -> Face Detection -> Landmarking & Alignment -> Feature Embedding Extraction -> Vector Search Matching -> Attendance Logging', tags: ['Python', 'OpenCV', 'InsightFace', 'Faiss', 'SQLite', 'Flask'], case: { Problem: 'Manual attendance is time-consuming and difficult to audit when groups are large or access points are distributed.', Approach: 'Faces are detected and aligned from RTSP streams, converted into InsightFace embeddings, matched with Faiss, and recorded in SQLite when confidence thresholds are met.', Evaluation: 'Verification precision, false-match behavior, stream quality tolerance, and duplicate attendance suppression were tested across enrolled identities.', Results: 'An automated attendance workflow that supports fast identity verification and an auditable attendance record.', Deployment: 'Served through Flask with SQLite logging and live RTSP stream processing.' } },
]

const filters = [['all', 'All'], ['ml', 'Machine Learning'], ['dl', 'Deep Learning'], ['cv', 'Computer Vision'], ['genai', 'Generative AI']]
const categoryLabels = { ml: 'Machine Learning', dl: 'Deep Learning', cv: 'Computer Vision', genai: 'Generative AI' }
const featuredProjectIds = ['rag', 'fracture', 'network-anomaly', 'custom-agent']
*/
const interests = ['Computer Vision', 'Medical Image Analysis', 'Object Detection', 'Deep Learning', 'NLP', 'Transformers', 'Generative AI', 'RAG', 'AI Agents', 'Multimodal AI', 'Efficient AI Systems']
const services = [['Machine Learning Development', 'Custom models, preprocessing, feature engineering, evaluation, and deployment.'], ['Computer Vision', 'Object detection, image classification, pose estimation, and real-time CV systems.'], ['Generative AI & RAG', 'LLM applications, document intelligence, embeddings, vector search, and AI assistants.'], ['Agentic AI', 'AI agents, tool calling, LangChain, LangGraph, and intelligent workflow automation.'], ['AI Application Development', 'Python, FastAPI, Streamlit, REST APIs, databases, and deployment-oriented applications.'], ['AI Research Support', 'Experimentation, model comparison, evaluation, technical research, and AI development.']]
const journey = [['Current', 'Applied AI Engineering'], ['Focus', 'CV + Deep Learning + GenAI'], ['Research', 'Applied AI Research & Publications'], ['Future', 'Advanced AI / ML Research'], ['Long-Term', 'Intelligent Multimodal Systems']]

function Eyebrow({ children }) { return <div className="eyebrow">{children}</div> }
function Section({ id, children, band = false }) { return <section className={`section ${band ? 'band' : ''}`} id={id}><div className="container">{children}</div></section> }
function Tags({ items }) { return <div className="tags">{items.map(item => <span className="tag" key={item}>{item}</span>)}</div> }

function App() {
  const [theme, setTheme] = useState('dark')
  const [menuOpen, setMenuOpen] = useState(false)
  const [filter, setFilter] = useState('all')
  const [selected, setSelected] = useState(null)

  useEffect(() => { document.documentElement.dataset.theme = theme }, [theme])
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add('show'); observer.unobserve(entry.target) }
    }), { threshold: 0.12 })
    document.querySelectorAll('.reveal').forEach(element => observer.observe(element))
    return () => observer.disconnect()
  }, [filter])

  const visibleProjects = projects.filter(project => filter === 'all' ? featuredProjectIds.includes(project.id) : getProjectCategories(project).includes(filter))
  const navItems = [['about', 'About'], ['skills', 'Skills'], ['experience', 'Experience'], ['projects', 'Projects'], ['research', 'Research'], ['certifications', 'Certifications'], ['contact', 'Contact']]
  const closeMenu = () => setMenuOpen(false)
  const featured = featuredProjectIds.slice(0, 3).map(projectId => projects.find(project => project.id === projectId))

  return <>
    <nav className="nav"><div className="nav-inner"><a href="#home" className="brand"><span className="brand-mark">MI</span><span>Muhammad Idrees</span></a><div className="nav-links">{navItems.map(item => <a href={`#${item[0]}`} key={item[0]}>{item[1]}</a>)}</div><div className="nav-actions"><a className="icon-btn" href="https://github.com/Muhammad-idrees05" target="_blank" rel="noreferrer" aria-label="GitHub">GH</a><a className="icon-btn" href="https://linkedin.com/in/muhammad-idreesa356822a" target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href="#contact" className="btn btn-primary nav-cta">Let's Work Together</a><button className="hamburger" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">☰</button></div></div></nav>
    <div className={`mobile-menu ${menuOpen ? 'open' : ''}`}>{navItems.map(item => <a href={`#${item[0]}`} key={item[0]} onClick={closeMenu}>{item[1]}</a>)}<a href="/Muhammad_Idrees.pdf" download="Muhammad_Idrees.pdf" onClick={closeMenu}>Download CV</a></div>

    <main>
      <section className="hero" id="home"><div className="hero-grid container"><div className="hero-copy reveal"><div className="eyebrow">AI ENGINEER · PESHAWAR, PAKISTAN</div><h1>Building intelligent systems <span>for the real world.</span></h1><p className="hero-lede">I design, evaluate, and deploy practical AI across Machine Learning, Deep Learning, Computer Vision, NLP, Generative AI, and Agentic AI.</p><div className="hero-badges">{['AI Engineer', 'ML Engineer', 'Computer Vision', 'Generative AI', 'Agentic AI'].map(badge => <span key={badge}>{badge}</span>)}</div><div className="hero-actions"><a href="#projects" className="btn btn-primary">View My Work <span>↗</span></a><a href="/Muhammad_Idrees.pdf" className="btn btn-quiet" download="Muhammad_Idrees.pdf">Download CV</a></div><div className="social-row"><a href="https://github.com/Muhammad-idrees05" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/muhammad-idreesa356822a" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="mailto:idreeskhan91905@gmail.com">Email ↗</a></div></div><div className="hero-art reveal"><div className="hero-profile"><img src="/idrees-profile.png" alt="Muhammad Idrees, AI Engineer"/><span><i/> Open to AI/ML roles</span></div></div></div><div className="stats-bar container">{[['04', 'AI disciplines'], ['20+', 'Technology tools'], ['01', 'Published paper']].map(stat => <div key={stat[1]}><strong>{stat[0]}</strong><span>{stat[1]}</span></div>)}</div></section>

      <section className="section about-section" id="about"><div className="container about-layout"><div className="section-intro reveal"><div className="eyebrow">01 / ABOUT</div><h2>From research question to reliable system.</h2></div><div className="about-content reveal"><p className="lead">I am a hands-on AI Engineer building useful systems where data, models, and product thinking meet.</p><p>My work spans structured experimentation, model evaluation, computer vision, document intelligence, RAG, agentic workflows, and deployment-oriented applications. I care about making AI understandable, measurable, and ready for the people who use it.</p><div className="capability-flow"><span>Research</span><b>→</b><span>Development</span><b>→</b><span>Experimentation</span><b>→</b><span>Deployment</span></div></div></div></section>

      <section className="section skills-section" id="skills"><div className="container"><div className="section-intro reveal"><div className="eyebrow">02 / CAPABILITIES</div><h2>The stack behind the systems.</h2><p>Organized around the full AI engineering lifecycle.</p></div><div className="skills-grid premium-skills">{skills.map((skill, index) => <div className="skill-cat reveal" key={skill[0]}><div className="skill-index">0{index + 1}</div><h3>{skill[0]}</h3><Tags items={skill[1]} /></div>)}</div></div></section>

      <section className="section experience-section" id="experience"><div className="container"><div className="section-intro reveal"><div className="eyebrow">03 / EXPERIENCE</div><h2>Applied AI, close to the work.</h2></div><div className="experience-list reveal"><article><div className="experience-date">AUG 2027 — PRESENT</div><div><h3>AI Engineer</h3><h4>ExatecSolution Peshawar</h4><p>Technical model evaluation, stakeholder communication, end-to-end AI/ML pipelines, data cleaning, EDA, feature engineering, data validation, hyperparameter optimization, and structured model experimentation.</p></div></article><article><div className="experience-date">FEB 2025 — AUG 2025</div><div><h3>AI Engineer</h3><h4>National Center of Artificial Intelligence (NCAI), UET Peshawar</h4><p>Practical AI/ML project pipelines across experimentation, model evaluation, applied research, and translating technical results into clear insights.</p></div></article></div></div></section>

      <section className="section projects-section" id="projects"><div className="container"><div className="section-intro project-intro reveal"><div className="eyebrow">04 / SELECTED WORK</div><h2>Systems I've built and evaluated.</h2><p>Four focused projects per discipline. Open any card for the full system story.</p></div><div className="filter-row reveal">{filters.map(item => <button className={filter === item[0] ? 'active' : ''} onClick={() => setFilter(item[0])} key={item[0]}>{item[1]}</button>)}</div><div className="project-grid premium-projects">{visibleProjects.map((project, index) => <article className="project-card reveal" style={{ '--delay': `${index * 70}ms` }} key={project.id} onClick={() => setSelected(project)}><div className="project-card-top"><span className="project-number">0{index + 1}</span><span className="pc-cat">{project.category.map(category => categoryLabels[category]).join(' · ')}</span></div><h3>{project.title}</h3><div className="pc-sub">{project.sub}</div><p>{project.desc}</p>{project.metric && <div className="metric"><strong>{project.metric}</strong><span>{project.metricLabel}</span></div>}<div className="card-tags"><Tags items={project.tags.slice(0, 5)} /></div><div className="card-action">View case study <span>↗</span></div></article>)}</div></div></section>

      <section className="section systems-section"><div className="container"><div className="section-intro reveal"><div className="eyebrow">05 / AI SYSTEMS</div><h2>AI systems I've built.</h2></div><div className="system-showcase">{featured.map((project, index) => <article className="system-row reveal" key={project.id}><div className="system-marker">0{index + 1}</div><div className="system-copy"><span className="pc-cat">{project.category.map(category => categoryLabels[category]).join(' · ')}</span><h3>{project.title}</h3><p>{project.desc}</p><div className="system-flow">{project.flow}</div></div><button onClick={() => setSelected(project)}>Explore <span>↗</span></button></article>)}</div></div></section>

      <section className="section architecture-section" id="architecture"><div className="container"><div className="section-intro reveal"><div className="eyebrow">06 / ENGINEERING</div><h2>Designed for the last mile.</h2><p>A repeatable path from raw signal to useful application.</p></div><div className="architecture-track reveal">{['Data', 'Preprocessing', 'ML / DL', 'LLM / CV / Agent', 'API', 'Deployment', 'Application'].map((node, index) => <div className="architecture-node" key={node}><span>{String(index + 1).padStart(2, '0')}</span><strong>{node}</strong>{index < 6 && <i>→</i>}</div>)}</div></div></section>

      <section className="section research-section" id="research"><div className="container split-section"><div className="section-intro reveal"><div className="eyebrow">07 / RESEARCH</div><h2>Experimentation with a point of view.</h2></div><article className="publication reveal"><span className="publication-type">PUBLISHED RESEARCH PAPER</span><h3>Enhancing K-Nearest Neighbors for Categorical Data Classification Using Similarity-Based Distance Metrics</h3><p>Research into improved similarity strategies for categorical classification, combining experimentation with clear technical communication.</p><span className="publication-tag">Machine Learning · Classification</span></article></div></section>

      <section className="section credentials-section" id="certifications"><div className="container credentials-grid"><div className="credential-block reveal"><div className="eyebrow">08 / EDUCATION</div><h2>Foundation</h2><div className="education-card"><span>BACHELOR OF SCIENCE</span><h3>Artificial Intelligence</h3><p>University of Agriculture, Peshawar</p><strong>3.40 <small>/ 4.00 CGPA</small></strong></div></div><div className="credential-block reveal"><div className="eyebrow">09 / CERTIFICATIONS</div><h2>Continuous learning.</h2><div className="cert-list">{[['Agentic AI', 'Edureka'], ['The Art of Prompt Engineering', 'IBM'], ['Prompt Engineering', 'Vanderbilt University'], ['Machine Learning, AI & Data Science', 'E-Hunar'], ['Feature Engineering for Machine Learning', 'Udemy']].map((cert, index) => <div key={cert[0]}><span>0{index + 1}</span><strong>{cert[0]}</strong><small>{cert[1]}</small></div>)}</div></div></div></section>

      <section className="section contact-section" id="contact"><div className="container contact-panel reveal"><div className="eyebrow">10 / CONTACT</div><h2>Have an AI idea?<br/><span>Let's build it.</span></h2><p>Whether it is a machine-learning model, computer-vision system, RAG application, AI agent, or automation workflow, let's talk.</p><div className="hero-actions"><a href="mailto:idreeskhan91905@gmail.com" className="btn btn-primary">Let's Talk ↗</a><a href="https://wa.me/923460972648" target="_blank" rel="noreferrer" className="btn btn-quiet">WhatsApp</a><a href="https://github.com/Muhammad-idrees05" target="_blank" rel="noreferrer" className="btn btn-quiet">View GitHub ↗</a><a href="https://linkedin.com/in/muhammad-idreesa356822a" target="_blank" rel="noreferrer" className="btn btn-quiet">LinkedIn ↗</a></div></div></section>
    </main>

    <footer><div className="container footer-inner"><div><div className="brand"><span className="brand-mark">MI</span><span>Muhammad Idrees</span></div><p>AI Engineer | Machine Learning | Computer Vision | Generative AI</p></div><div className="footer-links"><a href="https://github.com/Muhammad-idrees05">GitHub</a><a href="https://linkedin.com/in/muhammad-idreesa356822a">LinkedIn</a><a href="mailto:idreeskhan91905@gmail.com">Email</a></div><small>© 2026 Muhammad Idrees</small></div></footer>
    {selected && <div className="modal-overlay" onClick={event => event.target === event.currentTarget && setSelected(null)}><div className="modal premium-modal"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close case study">×</button><div className="modal-kicker">{selected.category.map(category => categoryLabels[category]).join(' · ')}</div><h2>{selected.title}</h2><p className="modal-subtitle">{selected.sub}</p>{selected.flow && <div className="modal-architecture"><span>Architecture</span><strong>{selected.flow}</strong></div>}<div className="modal-tags"><Tags items={selected.tags} /></div><div className="modal-sections">{Object.entries(selected.case).map(entry => <div key={entry[0]}><h4>{entry[0]}</h4><p>{entry[1]}</p></div>)}</div></div></div>}
  </>
}

export default App
